# -*- coding: utf-8 -*-
"""Performance Diagram with Color Gradient

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_Drwu_gdZm03g9jg0Fw1naiYlZKKPxE
"""

import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import sys
import subprocess
import os


#Function definition
def get_bias_label_position(bias_value, radius):
  x = np.sqrt(np.power(radius, 2)/(np.power(bias_value, 2)+1))
  y = np.sqrt(np.power(radius, 2) - np.power(x, 2))
  return (x, y)


def performance_diag():
  #INPUT file with CTC line
  CTCfile01 = os.environ['CTCfile01']
  row = np.loadtxt(CTCfile01, dtype=str, skiprows=1)
  #amodel = row[1:,10]
  #model = np.unique(amodel)
  total = row[1:,11]
  print('Printing total', total)
  hit = np.sum(np.array(row[1:,12], dtype=float))
  print('Printing hit', hit)
  falsea = np.sum(np.array(row[1:,13], dtype=float))
  print('Printing false alarms', falsea)
  miss = np.sum(np.array(row[1:,14], dtype=float))
  print('Printing misses', miss)
  hm = np.sum(np.add(hit, miss, dtype=float))
  print('Printing hit + misses', hm)
  hf = np.sum(np.add(hit, falsea, dtype=float))
  print('Printing hits + false alarms', hf)
  POD = np.sum(np.divide(hit, hm, out = np.zeros_like(hit), where = hm != 0))
  print('Printing POD', POD) #POD = hit/(hit + miss)
  FAR = np.sum(np.divide(hit, hf, out = np.zeros_like(hit), where = hf != 0))
  print('Printing FAR', FAR)  #FAR = falsea/(hit + falsea)
  SUR = 1.0 - FAR
  print('Printing SUR', SUR) #POD1 = POD + 0.03


  CTCfile02 = os.environ['CTCfile02']
  row = np.loadtxt(CTCfile02, dtype=str, skiprows=1)
  total2 = row[1:,11]
  print('Printing total 2', total2)
  hit2 = np.sum(np.array(row[1:,12], dtype=float))
  print('Printing hits 2', hit2)
  falsea2 = np.sum(np.array(row[1:,13], dtype=float))
  print('Printing false alarms 2', falsea2)
  miss2 = np.sum(np.array(row[1:,14], dtype=float))
  print('Printing misses 2', miss2)
  hm2 = np.sum(np.add(hit2, miss2, dtype=float))
  print('Printing hits + misses 2', hm2)
  hf2 = np.sum(np.add(hit2, falsea2, dtype=float))
  print('Printing hits + false alarms 2', hf2)
  POD2 = np.sum(np.divide(hit2, hm2, out = np.zeros_like(hit2), where = hm2 != 0))
  print('Printing POD2', POD2) #POD2 = hit2/(hit2 + miss2)
  FAR2 = np.sum(np.divide(hit2, hf2, out = np.zeros_like(hit2), where = hf2 != 0))
  print('Printing FAR2', FAR2) #FAR2 = falsea2/(hit2 + falsea2)
  SUR2 = 1.0 - FAR2
  print('Printing SUR2', SUR2)
  #POD2 = POD2 + 0.03


  CTCfile03 = os.environ['CTCfile03']
  row = np.loadtxt(CTCfile03, dtype=str, skiprows=1)
  total3 = row[1:,11]
  print('Printing total 3', total3)
  hit3 = np.sum(np.array(row[1:,12], dtype=float))
  print('Printing hits 3', hit3)
  falsea3 = np.sum(np.array(row[1:,13], dtype=float))
  print('Printing false alarms 3', falsea3)
  miss3 = np.sum(np.array(row[1:,14], dtype=float))
  print('Printing misses 3', miss3)
  hm3 = np.sum(np.add(hit3, miss3, dtype=float))
  print('Printing hit + misses 3', hm3)
  falsea3 = np.sum(np.array(row[1:,13], dtype=float))
  print('Printing false alarms 3', falsea3)
  miss3 = np.sum(np.array(row[1:,14], dtype=float))
  print('Printing misses 3', miss3)
  hm3 = np.sum(np.add(hit3, miss3, dtype=float))
  print('Printing hits + misses 3', hm3)
  hf3 = np.sum(np.add(hit3, falsea3, dtype=float))
  print('Printing hits + false alarms 3', hf3)
  POD3 = np.sum(np.divide(hit3, hm3, out = np.zeros_like(hit3), where = hm3 != 0))
  print('Printing POD3', POD3) #POD3 = hit3/(hit3 + miss3)
  FAR3 = np.sum(np.divide(hit3, hf3, out = np.zeros_like(hit3), where = hf3 != 0))
  print('Printing FAR3', FAR3) #FAR3 = falsea3/(hit3 + falsea3)
  SUR3 = 1.0 - FAR3
  print('Printing SUR3', SUR3)
  #POD3 = POD3 + 0.03

  CTCfile04 = os.environ['CTCfile04']
  row = np.loadtxt(CTCfile04, dtype=str, skiprows=1)
  total4 = row[1:,11]
  print('Printing total 4', total4)
  hit4 = np.sum(np.array(row[1:,12], dtype=float))
  print('Printing hits 4', hit4)
  falsea4 = np.sum(np.array(row[1:,13], dtype=float))
  print('Printing false alarms 4', falsea4)
  miss4 = np.sum(np.array(row[1:,14], dtype=float))
  print('Printing misses 4', miss4)
  hm4 = np.sum(np.add(hit4, miss4, dtype=float))
  print('Printing hits + misses 4', hm4)
  falsea4 = np.sum(np.array(row[1:,13], dtype=float))
  print('Printing false alarms 4', falsea4)
  miss4 = np.sum(np.array(row[1:,14], dtype=float))
  print('Printing misses 4', miss4)
  hm4 = np.sum(np.add(hit4, miss4, dtype=float))
  print('Printing hits + misses 4', hm4)
  hf4 = np.sum(np.add(hit4, falsea4, dtype=float))
  print('Printing hits + false alarms 4', hf4)
  POD4 = np.sum(np.divide(hit4, hm4, out = np.zeros_like(hit4), where = hm4 != 0))
  print('Printing POD4', POD4) #POD4 = hit4/(hit4 + miss4)
  FAR4 = np.sum(np.divide(hit4, hf4, out = np.zeros_like(hit4), where = hf4 != 0))
  print('Printing FAR4', FAR4) #FAR4 = falsea4/(hit4 + falsea4)
  SUR4 = 1.0 - FAR4
  print('Printing SUR4', SUR4)
  #POD4 = POD4 + 0.03

  CTCfile05 = os.environ['CTCfile05']
  row = np.loadtxt(CTCfile05, dtype=str, skiprows=1)
  total5 = row[1:,11]
  print('Printing total 5', total5)
  hit5 = np.sum(np.array(row[1:,12], dtype=float))
  print('Printing hits 5', hit5)
  falsea5 = np.sum(np.array(row[1:,13], dtype=float))
  print('Printing false alarms 5', falsea5)
  miss5 = np.sum(np.array(row[1:,14], dtype=float))
  print('Printing misses 5', miss5)
  hm5 = np.sum(np.add(hit5, miss5, dtype=float))
  print('Printing hits + misses 5', hm5)
  falsea5 = np.sum(np.array(row[1:,13], dtype=float))
  print('Printing false alarms 5', falsea5)
  miss5 = np.sum(np.array(row[1:,14], dtype=float))
  print('Printing misses 5', miss5)
  hm5 = np.sum(np.add(hit5, miss5, dtype=float))
  print('Printing hits + misses 5', hm5)
  hf5 = np.sum(np.add(hit5, falsea5, dtype=float))
  print('Printing hits + false alarms 5', hf5)
  POD5 = np.sum(np.divide(hit5, hm5, out = np.zeros_like(hit5), where = hm5 != 0))
  print('Printing POD5', POD5) #POD5 = hit5/(hit5 + miss5)
  FAR5 = np.sum(np.divide(hit5, hf5, out = np.zeros_like(hit5), where = hf5 != 0))
  print('Printing FAR5', FAR5) #FAR5 = falsea5/(hit5 + falsea5)
  SUR5 = 1.0 - FAR5
  print('Printing SUR5', SUR5)
  #POD5 = POD5 + 0.03

  CTCfile06 = os.environ['CTCfile06']
  row = np.loadtxt(CTCfile06, dtype=str, skiprows=1)
  total6 = row[1:,11]
  print('Printing total 6', total6)
  hit6 = np.sum(np.array(row[1:,12], dtype=float))
  print('Printing hits 6', hit6)
  falsea6 = np.sum(np.array(row[1:,13], dtype=float))
  print('Printing false alarms 6', falsea6)
  miss6 = np.sum(np.array(row[1:,14], dtype=float))
  print('Printing misses 6', miss6)
  hm6 = np.sum(np.add(hit6, miss6, dtype=float))
  print('Printing hits + misses 6', hm6)
  falsea6 = np.sum(np.array(row[1:,13], dtype=float))
  print('Printing false alarms 6', falsea6)
  miss6 = np.sum(np.array(row[1:,14], dtype=float))
  print('Printing misses 6', miss6)
  hm6 = np.sum(np.add(hit6, miss6, dtype=float))
  print('Printing hits + misses 6', hm6)
  hf6 = np.sum(np.add(hit6, falsea6, dtype=float))
  print('Printing hits + false alarms 6', hf6)
  POD6 = np.sum(np.divide(hit6, hm6, out = np.zeros_like(hit6), where = hm6 != 0))
  print('Printing POD6', POD6) #POD6 = hit6/(hit6 + miss6)
  FAR6 = np.sum(np.divide(hit6, hf6, out = np.zeros_like(hit6), where = hf6 != 0))
  print('Printing FAR6', FAR6) #FAR6 = falsea6/(hit6 + falsea6)
  SUR6 = 1.0 - FAR6
  print('Printing SUR6', SUR6)
  #POD6 = POD6 + 0.03

  # --- Code added to calculate CSI for color gradient ---
  # Critical Success Index (CSI) for each model.
  # Handles division by zero for cases where SUR or POD are zero.
  csi_hfsa = 1 / ((1 / SUR) + (1 / POD) - 1) if SUR != 0 and POD != 0 else 0
  csi_hfsb = 1 / ((1 / SUR2) + (1 / POD2) - 1) if SUR2 != 0 and POD2 != 0 else 0
  csi_hwrf = 1 / ((1 / SUR3) + (1 / POD3) - 1) if SUR3 != 0 and POD3 != 0 else 0
  csi_hmon = 1 / ((1 / SUR4) + (1 / POD4) - 1) if SUR4 != 0 and POD4 != 0 else 0
  csi_gfs = 1 / ((1 / SUR5) + (1 / POD5) - 1) if SUR5 != 0 and POD5 != 0 else 0
  csi_ctcx = 1 / ((1 / SUR6) + (1 / POD6) - 1) if SUR6 != 0 and POD6 != 0 else 0

  #Output file name
  rirw_thresh = os.environ['rirw_thresh']
  #stormBasin = os.environ['stormBasin']
  outf = f"tcrirw_performance_diagram_{rirw_thresh}.png"
  print(outf)

  #Define figure, plot axis
  fig = plt.figure(figsize=(8,8))
  ax = fig.add_axes([0.1, 0.1, 0.8, 0.8])


  #Define range for x, y; create 2D array of x, y values
  x = np.arange(0.001,1.01,0.01)
  y = np.arange(0.001,1.01,0.01)
  xi,yi = np.meshgrid(x, y)


  #Calculate bias and CSI; set contour levels
  bias = yi/xi
  blevs = [0.1, 0.25, 0.5, 0.75, 1, 1.25, 2.5, 5, 10]
  csi = 1/( (1/xi) + (1/yi) - 1 )
  csilevs = np.arange(0.1,1,0.1)


  #The second way-Calculate bias and CSI; set contour levels
  grid_ticks = np.arange(0.001, 1.01, 0.01)
  sr_g, pod_g = np.meshgrid(grid_ticks, grid_ticks)
  biasp = pod_g / sr_g
  csip = 1.0 / (1.0 / sr_g + 1.0 / pod_g - 1.0)

  # --- Code added to create a filled contour gradient ---
  # Create a filled contour plot for CSI as the background
  csi_contourf = plt.contourf(
      sr_g,
      pod_g,
      csip,
      np.arange(0.1, 1.1, 0.1),
      extend="max",
      cmap="YlGnBu" # Using a blue-green color map
  )

  # Add a color bar for the filled CSI contours
  cbar = plt.colorbar(csi_contourf)
  cbar.set_label('Critical Success Index', fontsize=12, fontweight='bold')

  # Re-plot the CSI contour lines on top of the gradient for clarity
  ccsi = ax.contour(
      sr_g,
      pod_g,
      csip,
      csilevs,
      colors='white', # Changed color to white for better contrast
      linewidths=1,
      linestyles='-')

  plt.clabel(ccsi,csilevs,inline=True,fmt='%.1f',fontsize=10,colors='black')


  bias_contour_vals = [0.1, 0.3, 0.6, 1., 1.5, 3., 10.]
  b_contour = plt.contour(sr_g, pod_g, biasp, bias_contour_vals,colors='gray', linestyles='--')
  plt.clabel(
      b_contour, fmt='%1.1f',
      manual=[
          get_bias_label_position(bias_value, .75)
          for bias_value in bias_contour_vals
      ]
  )


  #Axis labels, tickmarks
  ax.set_xlabel('Success Ratio (1 - False Alarm Ratio)',fontsize=12,fontweight='bold')
  ax.set_ylabel('Probability of Detection',fontsize=12,fontweight='bold')
  ax.set_xticks(np.arange(0,1.1,0.1))
  ax.set_yticks(np.arange(0,1.1,0.1))
  plt.setp(ax.get_xticklabels(),fontsize=13)
  plt.setp(ax.get_yticklabels(),fontsize=13)


  #Second y-axis for bias values < 1
#  ax2 = ax.twinx()
#  ax2.set_yticks(blevs[0:5])
#  plt.setp(ax2.get_yticklabels(),fontsize=13)


  #Axis labels for bias values > 1
#  ax.text(0.1,1.015,'10',fontsize=13,va='center',ha='center')
#  ax.text(0.2,1.015,'5',fontsize=13,va='center',ha='center')
#  ax.text(0.4,1.015,'2.5',fontsize=13,va='center',ha='center')
#  ax.text(0.8,1.015,'1.25',fontsize=13,va='center',ha='center')


  #Plot bias and CSI lines at specified contour intervals
#  cbias =  ax.contour(x,y,bias,blevs,colors='black',linewidths=1,linestyles='--')
#  ccsi =  ax.contour(x,y,csi,csilevs,colors='gray',linewidths=1,linestyles='-')
#  plt.clabel(ccsi,csilevs,inline=True,fmt='%.1f',fontsize=10,colors='black')


  # --- Reverting data points to solid black for contrast ---
  # Group the data into arrays for plotting
  sur_values = np.array([SUR, SUR2, SUR3, SUR4, SUR5, SUR6])
  pod_values = np.array([POD, POD2, POD3, POD4, POD5, POD6])
  model_names = ['HFSA', 'HFSB', 'HWRF', 'HMON', 'GFS', 'CTCX']

  # Plot points with solid black color
  ax.scatter(
      sur_values,
      pod_values,
      c='black',
      s=100,
      edgecolors='white',
      linewidths=2,
      zorder=5
  )

  # Add text labels next to each point
  for i, name in enumerate(model_names):
      ax.text(
          sur_values[i] + 0.02,
          pod_values[i],
          name,
          fontsize=10,
          fontweight='bold',
          ha='left',
          va='center',
          color='black'
      )

  # --- The old data plotting code is now commented out ---
  # ax.plot(SUR,POD,marker='o',markersize=10,c='#8400C8')
  # ax.plot(SUR2,POD2,marker='o',markersize=10,c='#00DC00')
  # ax.plot(SUR3,POD3,marker='o',markersize=10,c='#E63B7F')
  # ax.plot(SUR4,POD4,marker='o',markersize=10,c='#49D9DE')
  # ax.plot(SUR5,POD5,marker='o',markersize=10,c='#000000')
  # ax.plot(SUR6,POD6,marker='o',markersize=10,c='#4287F5')
  # ax.plot(0.13,0.95,marker='o',markersize=5,c='#8400C8')
  # ax.text(0.17,0.95,'HFSA',fontsize=7,fontweight='bold',ha='center',va='center',color='#8400C8')
  # ax.plot(0.23,0.95,marker='o',markersize=5,c='#00DC00')
  # ax.text(0.27,0.95,'HFSB',fontsize=7,fontweight='bold',ha='center',va='center',color='#00DC00')
  # ax.plot(0.33,0.95,marker='o',markersize=5,c='#E63B7F')
  # ax.text(0.37,0.95,'HWRF',fontsize=7,fontweight='bold',ha='center',va='center',color='#E63B7F')
  # ax.plot(0.43,0.95,marker='o',markersize=5,c='#49D9DE')
  # ax.text(0.47,0.95,'HMON',fontsize=7,fontweight='bold',ha='center',va='center',color='#49D9DE')
  # ax.plot(0.53,0.95,marker='o',markersize=5,c='#000000')
  # ax.text(0.57,0.95,'GFS',fontsize=7,fontweight='bold',ha='center',va='center',color='#000000')
  # ax.plot(0.63,0.95,marker='o',markersize=5,c='#4287F5')
  # ax.text(0.67,0.95,'CTCX',fontsize=7,fontweight='bold',ha='center',va='center',color='#4287F5')


  # Build formal plot title
  full_title = 'RI/RW Performance Diagram'
  #full_title = formal_stat_name+'\n'
  #full_title = ""
#  if basin == 'al':
#    formal_basin = 'Atlantic'
#  elif basin == 'cp':
#    formal_basin = 'Central Pacific'
#  elif basin == 'ep':
#    formal_basin = 'Eastern Pacific'
#  elif basin == 'wp':
#    formal_basin = 'Western Pacific'
#  if len(plot_info) == 2:
#    full_title = full_title+formal_basin+' Mean\n'
#  else:
#    full_title = full_title + name.title().upper() + ' ' + '(' + basin + str(tc_num) + ' ' + year + ')'
  #full_title = (full_title+'Cycles: '+', '.join(init_hour_list)+', '
  #Valid Hours: '+', '.join(valid_hour_list))
  ax.set_title(full_title)
#  noaa_img = fig.figimage(noaa_logo_img_array,
#  noaa_logo_xpixel_loc, noaa_logo_ypixel_loc,
#  zorder=1, alpha=noaa_logo_alpha)
#  nws_img = fig.figimage(nws_logo_img_array,
#  nws_logo_xpixel_loc, nws_logo_ypixel_loc,
#  zorder=1, alpha=nws_logo_alpha)


  title="Performance Diagram"
  plt.title(title, fontsize=12, fontweight="bold")
  #TCRIRWcases = os.environ['TCRIRWcases']
  #plt.title('Rapid Intensification/Weakening', fontsize=12, fontweight="bold")

  #Save, close, and trim whitespace around plot
  #plt.savefig(outf,pad_inches=0.01, orientation='landscape')
  #plt.savefig(outf)
  plt.savefig(outf, dpi=160, bbox_inches='tight')
  plt.close()
  #subprocess.call("convert -trim "+outf+" "+outf, shell=True)


#Function call
performance_diag()


sys.exit()